feat/3: Added new config to allow users to toggle total card counters
Balastrong/trello-card-numbers-plus pull request #28
Opened 2022-12-10 20:21 UTC by jbarbosa7

This PR fixes #3 

- Added a new config to allow users to toggle the total card counters labels

2022-12-11 17:39 UTC, Balastrong requested changes
Thank you for the PR, I see the code style of the project is perfectly matched, well done!

I added a little note in the other comment, everything else looks good :)

2022-12-12 10:54 UTC, jbarbosa7 commented on public/popup.html
>            <div class="config-label">Active</div>
Great catch! I actually thought about that but then forgot to change it 😓 I'll update this as soon as i can :)

2022-12-12 23:53 UTC, jbarbosa7 commented
> Thank you for the PR, I see the code style of the project is perfectly matched, well done!
> 
> I added a little note in the other comment, everything else looks good :)

@Balastrong 

> Thank you for the PR, I see the code style of the project is perfectly matched, well done!
> 
> I added a little note in the other comment, everything else looks good :)

Already updated the PR with your sugestion :)

2022-12-13 09:28 UTC, Balastrong approved these changes
Thank you :D

2022-12-13 09:29 UTC, merged